
"use client";

import AISetupAssistant from '@/components/ai-setup-assistant';
import { useState } from 'react';
import { useToast } from "@/hooks/use-toast";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from '@/components/ui/badge';
import { ListTodo } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type ManagedTask = {
    id: number;
    description: string;
    frequency: string;
    assignee: string;
};

// Mock data, in a real app this would come from a database.
const teamMembers = [
    { name: "John Doe" },
    { name: "Jane Smith" },
    { name: "Sam Wilson" },
    { name: "Alice Brown" },
];


export default function EquipmentPage() {
    const { toast } = useToast();
    const [managedTasks, setManagedTasks] = useState<ManagedTask[]>([]);
    
    const handleGeneratedTasks = (generatedTasks: { description: string, frequency: string }[]) => {
        const newTasks = generatedTasks.map((task, index) => ({
            id: (managedTasks.length > 0 ? Math.max(...managedTasks.map(t => t.id)) : 0) + index + 1,
            description: task.description,
            frequency: task.frequency,
            assignee: 'Unassigned',
        }));

        setManagedTasks(prevTasks => [...newTasks, ...prevTasks]);

        toast({
            title: "Task Checklist Generated!",
            description: `${newTasks.length} new tasks have been added to the 'Generated Tasks' list below.`,
        });
    };

    const handleAssignTask = (taskId: number, assignee: string) => {
        setManagedTasks(prevTasks =>
            prevTasks.map(task =>
                task.id === taskId ? { ...task, assignee } : task
            )
        );
        toast({
            title: "Task Assigned",
            description: `Task has been assigned to ${assignee}.`,
        });
    };

    return (
        <div className="space-y-6">
            <AISetupAssistant onTasksGenerated={handleGeneratedTasks} />

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline flex items-center gap-2"><ListTodo /> Generated Tasks</CardTitle>
                    <CardDescription>
                        This is the list of tasks generated by the AI based on your equipment. Assign them to team members below.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead className="w-[60%]">Task</TableHead>
                                <TableHead>Frequency</TableHead>
                                <TableHead>Assignee</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {managedTasks.length > 0 ? (
                                managedTasks.map((task) => (
                                <TableRow key={task.id}>
                                    <TableCell className="font-medium">{task.description}</TableCell>
                                    <TableCell>
                                        <Badge variant="secondary">{task.frequency}</Badge>
                                    </TableCell>
                                    <TableCell>
                                        <Select
                                            value={task.assignee}
                                            onValueChange={(value) => handleAssignTask(task.id, value)}
                                        >
                                            <SelectTrigger className="w-[180px]">
                                                <SelectValue placeholder="Assign..." />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="Unassigned">Unassigned</SelectItem>
                                                {teamMembers.map(member => (
                                                    <SelectItem key={member.name} value={member.name}>
                                                        {member.name}
                                                    </SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </TableCell>
                                </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                <TableCell colSpan={3} className="text-center h-24">
                                    No tasks generated yet. Use the AI Setup Assistant above to create a task list.
                                </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
}
