
"use client";

import AISetupAssistant from '@/components/ai-setup-assistant';
import { useState } from 'react';
import { useToast } from "@/hooks/use-toast";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from '@/components/ui/badge';
import { ListTodo } from 'lucide-react';

type ManagedTask = {
    id: number;
    description: string;
    frequency: string;
    assignee: string;
};

export default function EquipmentPage() {
    const { toast } = useToast();
    const [managedTasks, setManagedTasks] = useState<ManagedTask[]>([]);
    
    const handleGeneratedTasks = (generatedTasks: { description: string, frequency: string }[]) => {
        const newTasks = generatedTasks.map((task, index) => ({
            id: (managedTasks.length > 0 ? Math.max(...managedTasks.map(t => t.id)) : 0) + index + 1,
            description: task.description,
            frequency: task.frequency,
            assignee: 'Unassigned',
        }));

        setManagedTasks(prevTasks => [...newTasks, ...prevTasks]);

        toast({
            title: "Task Checklist Generated!",
            description: `${newTasks.length} new tasks have been added to the 'Generated Tasks' list below.`,
        });
    };

    return (
        <div className="space-y-6">
            <AISetupAssistant onTasksGenerated={handleGeneratedTasks} />

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline flex items-center gap-2"><ListTodo /> Generated Tasks</CardTitle>
                    <CardDescription>
                        This is the list of tasks generated by the AI based on your equipment. You can assign these from the main dashboard.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Task</TableHead>
                                <TableHead>Assignee</TableHead>
                                <TableHead>Frequency</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {managedTasks.length > 0 ? (
                                managedTasks.map((task) => (
                                <TableRow key={task.id}>
                                    <TableCell className="font-medium">{task.description}</TableCell>
                                    <TableCell>{task.assignee}</TableCell>
                                    <TableCell>
                                        <Badge variant="secondary">{task.frequency}</Badge>
                                    </TableCell>
                                </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                <TableCell colSpan={3} className="text-center h-24">
                                    No tasks generated yet. Use the AI Setup Assistant above to create a task list.
                                </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
}
