"use client"

import { useCollection } from "react-firebase-hooks/firestore"
import { db } from "@/lib/firebase"
import { collection, query, orderBy, limit } from "firebase/firestore"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Bell, Loader2 } from "lucide-react"

export default function LiveAlertFeed() {
  const [snapshot, loading, error] = useCollection(
    query(collection(db, "alerts"), orderBy("timestamp", "desc"), limit(10))
  )
  const alerts = snapshot?.docs.map(doc => ({ id: doc.id, ...doc.data() as { title: string, agentId: string, timestamp: number } })) ?? []

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
            <Bell /> Live Alert Feed
        </CardTitle>
        <CardDescription>
            A real-time stream of the latest 10 alerts generated by AI agents.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {loading && (
            <div className="flex items-center justify-center p-4">
                <Loader2 className="mr-2 h-4 w-4 animate-spin"/> Loading alerts...
            </div>
        )}
        {error && <p className="text-destructive">Error: {error.message}</p>}
        {!loading && alerts.length === 0 && (
            <p className="text-center text-muted-foreground p-4">No alerts found.</p>
        )}
        <ul className="space-y-4 text-sm">
          {alerts.map((alert) => (
            <li key={alert.id} className="border-b pb-2">
              <p className="font-semibold">{alert.title}</p>
              <p className="text-xs text-muted-foreground">
                Agent: {alert.agentId} at {new Date(alert.timestamp).toLocaleTimeString()}
              </p>
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  )
}
